;;; relint-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from relint.el

(autoload 'relint-file "relint" "\
Scan FILE, an elisp file, for regexp-related errors.

(fn FILE)" t)
(autoload 'relint-directory "relint" "\
Scan all *.el files in DIR for regexp-related errors.

(fn DIR)" t)
(autoload 'relint-current-buffer "relint" "\
Scan the current buffer for regexp errors.
The buffer must be in emacs-lisp-mode." t)
(autoload 'relint-buffer "relint" "\
Scan BUFFER for regexp mistakes. Return list of diagnostics.
Each element in the returned list is an object with the slots

  message    the message string
  beg-pos    starting position in the buffer
  end-pos    ending position the buffer (inclusive), or nil
  pos-type   if `string', then the buffer at BEG-POS..END-POS is inside
             a string literal corresponding to STRING at BEG-IDX..END-IDX;
             otherwise BEG-POS..END-POS just point to code
  string     the string the message is about, or nil
  beg-idx    starting offset in STRING, or nil
  end-idx    ending offset in STRING (inclusive), or nil
  severity   `error', `warning' or `info'

Accessors are prefixed by `relint-diag-': eg, (relint-diag-message D) returns
the message of object D.

BEG-POS..END-POS is the range of interest in the buffer, and may
correspond to the range BEG-IDX..END-IDX in STRING but not necessarily so.

(fn BUFFER)")
(register-definition-prefixes "relint" '("relint-"))

;;; End of scraped data

(provide 'relint-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; relint-autoloads.el ends here
