;;; mu4e-autotask-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from mu4e-autotask.el

(autoload 'mu4e-autotask-dispatch "mu4e-autotask" "\
Run the matching `mu4e-autotask-rules' automation for mu4e MSG.
`mu4e-autotask-pre-action-hook' runs first; a member that signals an error
aborts the dispatch.  Signal a `user-error', without running any action, if
more than one rule matches.  Signal a `user-error' first if any rule in
`mu4e-autotask-rules' sets conflicting match criteria, regardless of whether it
would match MSG.  When no rule matches, MSG carries the mu `calendar' flag,
and `mu4e-autotask-handle-icalendar' is non-nil, run the built-in calendar
invitation handler instead.
Call this from a `mu4e-view-mode' or `mu4e-headers-mode' buffer, as the
`mu4e-view-actions' entry does: the calendar invitation handler replies via
`mu4e-compose-reply-to', which needs the message at point.

(fn MSG)")
(autoload 'mu4e-autotask-initialize "mu4e-autotask" "\
Register the automation dispatcher as a mu4e view action.
Adds an \"Execute automation\" entry to `mu4e-view-actions'.")
(autoload 'mu4e-autotask-do-send-email "mu4e-autotask" "\
Ask to send the message in the current compose buffer, to TO.
The \"To:\" field of the email must already be filled out; TO is used only for
the confirmation prompt.  Call SUCCESS-FN only after the message is sent; on a
declined send, discard the compose buffer and signal a `user-error'.  An error
or quit SUCCESS-FN signals is downgraded to a warning: the message is already
sent at that point, so the failure of a follow-up action must not present as a
failed send.

This is the building block behind `mu4e-autotask-send-email', exposed for action
functions that compose a message themselves (e.g. a forward or reply) and then
want the same confirm-and-send behavior.

(fn TO SUCCESS-FN)")
(autoload 'mu4e-autotask-send-email "mu4e-autotask" "\
Compose and send mail from TEMPLATE, call SUCCESS-FN once it is sent.
TEMPLATE is a `mu4e-autotask-email-template'.  ATTACHMENTS is a list of file
paths to attach.  SUCCESS-FN is called only after the message is sent.

(fn TEMPLATE ATTACHMENTS SUCCESS-FN)")
(register-definition-prefixes "mu4e-autotask" '("mu4e-autotask-"))

;;; End of scraped data

(provide 'mu4e-autotask-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mu4e-autotask-autoloads.el ends here
