;;; org-sticky-header-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-sticky-header.el

(autoload 'org-sticky-header-mode "org-sticky-header" "\
Minor mode to show the current Org heading in the header line.
With prefix argument ARG, turn on if positive, otherwise off.
Return non-nil if the minor mode is enabled.

(fn &optional ARG)" t)
(register-definition-prefixes "org-sticky-header" '("org-sticky-header-"))

;;; End of scraped data

(provide 'org-sticky-header-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-sticky-header-autoloads.el ends here
