;;; mcp-server-lib-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from mcp-server-lib.el

(register-definition-prefixes "mcp-server-lib" '("mcp-server-lib-"))


;;; Generated autoloads from mcp-server-lib-commands.el

(autoload 'mcp-server-lib-start "mcp-server-lib-commands" "\
Start the MCP server and begin handling client requests.

This function starts the MCP server that can process JSON-RPC
requests via `mcp-server-lib-process-jsonrpc'.  Once started, the server
will dispatch incoming requests to the appropriate tool
handlers that have been registered with `mcp-server-lib-register-tool'.

Resets all metrics when starting.

See also: `mcp-server-lib-stop'" t)
(autoload 'mcp-server-lib-stop "mcp-server-lib-commands" "\
Stop the MCP server from processing client requests.

Sets the server state to stopped, which prevents further processing of
client requests.  Note that this does not release any resources or unregister
tools, it simply prevents `mcp-server-lib-process-jsonrpc' from accepting new
requests.

See also: `mcp-server-lib-start'" t)
(autoload 'mcp-server-lib-install "mcp-server-lib-commands" "\
Install emacs-mcp-stdio.sh to `mcp-server-lib-install-directory'." t)
(autoload 'mcp-server-lib-uninstall "mcp-server-lib-commands" "\
Remove installed emacs-mcp-stdio.sh from `mcp-server-lib-install-directory'." t)
(autoload 'mcp-server-lib-reset-metrics "mcp-server-lib-commands" "\
Reset all metrics." t)
(autoload 'mcp-server-lib-show-metrics "mcp-server-lib-commands" "\
Display metrics in a buffer." t)
(register-definition-prefixes "mcp-server-lib-commands" '("mcp-server-lib--"))


;;; Generated autoloads from mcp-server-lib-ert.el

(register-definition-prefixes "mcp-server-lib-ert" '("mcp-server-lib-ert-check-text-response"))


;;; Generated autoloads from mcp-server-lib-metrics.el

(register-definition-prefixes "mcp-server-lib-metrics" '("mcp-server-lib-metrics-"))

;;; End of scraped data

(provide 'mcp-server-lib-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mcp-server-lib-autoloads.el ends here
