;;; difftastic-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from difftastic.el

(autoload 'difftastic-git-diff-range "difftastic" "\
Show difference between two commits using difftastic.
The meaning of REV-OR-RANGE, ARGS, and FILES is like in
`magit-diff-range', but ARGS are adjusted for difftastic with
`difftastic--transform-diff-arguments'.

(fn &optional REV-OR-RANGE ARGS FILES)" t)
(autoload 'difftastic-magit-diff "difftastic" "\
Show the result of \\='git diff ARGS -- FILES\\=' with difftastic.

(fn &optional ARGS FILES)" t)
(autoload 'difftastic-magit-show "difftastic" "\
Show the result of \\='git show REV\\=' with difftastic.
When REV couldn't be guessed or called with prefix arg ask for REV.

(fn REV)" t)
(autoload 'difftastic-buffers "difftastic" "\
Run difftastic on a pair of buffers, BUFFER-A and BUFFER-B.
Optionally, provide a LANG-OVERRIDE to override language used.
See \\='difft --list-languages\\=' for language list.

When:
- either LANG-OVERRIDE is nil and neither of BUFFER-A nor
BUFFER-B is a file buffer,
- or function is called with a prefix arg,

then ask for language before running difftastic.

(fn BUFFER-A BUFFER-B &optional LANG-OVERRIDE)" t)
(autoload 'difftastic-files "difftastic" "\
Run difftastic on a pair of files, FILE-A and FILE-B.
Optionally, provide a LANG-OVERRIDE to override language used.
See \\='difft --list-languages\\=' for language list.  When
function is called with a prefix arg then ask for language before
running difftastic.

(fn FILE-A FILE-B &optional LANG-OVERRIDE)" t)
(autoload 'difftastic-dired-diff "difftastic" "\
Compare file at point with FILE using difftastic.
The behavior is the same as `dired-diff', except for the prefix argument, which
makes the function prompt for LANG-OVERRIDE.  See \\='difft
--list-languages\\=' for language list.

(fn FILE &optional LANG-OVERRIDE)" '(dired-mode))
(autoload 'difftastic-rerun "difftastic" "\
Rerun difftastic in the current buffer.
Optionally, provide a LANG-OVERRIDE to override language used.
See \\='difft --list-languages\\=' for language list.  When
function is called with a prefix arg then ask for language before
running difftastic.

In order to determine requested width for difftastic a call to
`difftastic-rerun-requested-window-width-function' is made.  When
the latter is set to nil the call is made to
`difftastic-requested-window-width-function'.

(fn &optional LANG-OVERRIDE)" '(difftastic-mode))
(register-definition-prefixes "difftastic" '("difftastic-"))


;;; Generated autoloads from difftastic-bindings.el

(defvar difftastic-bindings-prefixes '((magit-diff (-1 -1) magit-diff) (magit-blame (-1) magit-blame)) "\
List of prefixes to install `difftastic' bindings.
Each entry in the list is in a from of (PREFIX LOC FEATURE),
where PREFIX is a `transient' prefix to which to install
bindings, LOC is a location within the prefix and FEATURE is a
feature (symbol) or file (string) that defines the prefix.  LOC
can be in any form accepted by `transient-get-suffix', which see.")
(custom-autoload 'difftastic-bindings-prefixes "difftastic-bindings" t)
(defvar difftastic-bindings-keymaps '((magit-blame-read-only-mode-map . magit-blame)) "\
List of keymaps to add `difftastic' bindings to.
Each entry in the list is in a form of (MAP . FEATURE), where MAP
is a keymap to set bindings to and FEATURE is a feature (symbol)
or file (string) that defines the MAP.")
(custom-autoload 'difftastic-bindings-keymaps "difftastic-bindings" t)
(defvar difftastic-bindings-alist '(("D" difftastic-magit-diff "Difftastic diff (dwim)") ("S" difftastic-magit-show "Difftastic show")) "\
Define `difftastic' bindings.
Each entry is in a form of (KEY COMMAND DESCRIPTION), where KEY
is a key that should be bound, COMMAND is a command that should
be executed when KEY has been pressed, and DESCRIPTION is a
description that should be used for suffixes that are added to
prefixes as defined in `difftastic-bindings-prefixes'.  KEY needs
to be a valid key according to `key-valid-p' and in a form
accepted by `transient-append-suffix'.")
(custom-autoload 'difftastic-bindings-alist "difftastic-bindings" t)
(defvar difftastic-bindings-mode nil "\
Non-nil if Difftastic-Bindings mode is enabled.
See the `difftastic-bindings-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `difftastic-bindings-mode'.")
(custom-autoload 'difftastic-bindings-mode "difftastic-bindings" nil)
(autoload 'difftastic-bindings-mode "difftastic-bindings" "\
Ensure key bindings to `difftastic' commands.

Use bindings specified in `difftastic-bindings' (which see) to
create a suffixes in prefixes defined in
`difftastic-bindings-prefixes' (which see) and install them into
`difftastic-bindings-keymaps' (which see).

This is a global minor mode.  If called interactively, toggle the
`Difftastic-Bindings mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='difftastic-bindings-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "difftastic-bindings" '("difftastic-bindings-"))

;;; End of scraped data

(provide 'difftastic-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; difftastic-autoloads.el ends here
