;;; elisp-dev-mcp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from elisp-dev-mcp.el

(autoload 'elisp-dev-mcp-enable "elisp-dev-mcp" "\
Enable the Elisp development MCP tools.")
(autoload 'elisp-dev-mcp-disable "elisp-dev-mcp" "\
Disable the Elisp development MCP tools.")
(register-definition-prefixes "elisp-dev-mcp" '("elisp-dev-mcp--"))

;;; End of scraped data

(provide 'elisp-dev-mcp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; elisp-dev-mcp-autoloads.el ends here
