;;; helm-dash-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-dash.el

(autoload 'helm-dash-activate-docset "helm-dash" "\
Activate DOCSET.  If called interactively prompts for the docset name.

(fn DOCSET)" t)
(autoload 'helm-dash-deactivate-docset "helm-dash" "\
Deactivate DOCSET.  If called interactively prompts for the docset name.

(fn DOCSET)" t)
(autoload 'helm-dash-install-user-docset "helm-dash" "\
Download an unofficial docset with specified DOCSET-NAME and move its stuff to docsets-path.

(fn DOCSET-NAME)" t)
(autoload 'helm-dash-install-docset-from-file "helm-dash" "\
Extract the content of DOCSET-TMP-PATH, move it to `helm-dash-docsets-path` and activate the docset.

(fn DOCSET-TMP-PATH)" t)
(autoload 'helm-dash-install-docset "helm-dash" "\
Download an official docset with specified DOCSET-NAME and move its stuff to docsets-path.

(fn DOCSET-NAME)" t)
(autoload 'helm-dash-async-install-docset "helm-dash" "\
Asynchronously download docset with specified DOCSET-NAME and move its stuff to docsets-path.

(fn DOCSET-NAME)" t)
(autoload 'helm-dash-async-install-docset-from-file "helm-dash" "\
Asynchronously extract the content of DOCSET-TMP-PATH, move it to `helm-dash-docsets-path` and activate the docset.

(fn DOCSET-TMP-PATH)" t)
(autoload 'helm-dash-ensure-docset-installed "helm-dash" "\
Install DOCSET if it is not currently installed.

(fn DOCSET)")
(autoload 'helm-dash "helm-dash" "\
Bring up a `helm-dash' search interface.
If INPUT-PATTERN is non-nil, use it as an initial input in helm search.

(fn &optional INPUT-PATTERN)" t)
(autoload 'helm-dash-at-point "helm-dash" "\
Bring up a `helm-dash' search interface with symbol at point." t)
(register-definition-prefixes "helm-dash" '("helm-"))

;;; End of scraped data

(provide 'helm-dash-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-dash-autoloads.el ends here
