;;; wgrep-deadgrep-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from wgrep-deadgrep.el

(autoload 'wgrep-deadgrep-setup "wgrep-deadgrep" "\
Setup `wgrep-deadgrep' for `deadgrep'.")
(add-hook 'deadgrep-finished-hook 'wgrep-deadgrep-setup)
(register-definition-prefixes "wgrep-deadgrep" '("wgrep-deadgrep-"))

;;; End of scraped data

(provide 'wgrep-deadgrep-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; wgrep-deadgrep-autoloads.el ends here
