;;; stripe-buffer-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from stripe-buffer.el

(autoload 'stripe-buffer-mode "stripe-buffer" "\
Stripe buffer mode

This is a minor mode.  If called interactively, toggle the
`Stripe-Buffer mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `stripe-buffer-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'turn-on-stripe-buffer-mode "stripe-buffer" "\
Turn on `stripe-buffer-mode'." t)
(autoload 'stripe-table-mode "stripe-buffer" "\
Stripe table mode

This is a minor mode.  If called interactively, toggle the
`Stripe-Table mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `stripe-table-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'turn-on-stripe-table-mode "stripe-buffer" "\
Turn on `stripe-table-mode'." t)
(autoload 'org-table-stripes-enable "stripe-buffer" "\
Backward compatibility" t)
(autoload 'stripe-listify-buffer "stripe-buffer" "\
Turn on `stripe-buffer-mode' and `hl-line-mode'." t)
(register-definition-prefixes "stripe-buffer" '("sb/" "stripe-"))

;;; End of scraped data

(provide 'stripe-buffer-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; stripe-buffer-autoloads.el ends here
