name: Emacs Lisp CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - snapshot
          - 29.4
          - 28.2
          - 27.2
          - 26.3
          - 25.3
          - 24.5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: Install dependencies
      run: |
        emacs -Q --batch \
              --eval "(require 'package)" \
              --eval "(add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\") t)" \
              --eval "(package-initialize)" \
              --eval "(package-refresh-contents)" \
              --eval "(package-install 'package-lint)"

    - name: Byte-compile
      run: |
        emacs -Q --batch \
          --eval "(setq byte-compile-error-on-warn t)" \
          -f batch-byte-compile emacs/.emacs.d/my/my-org-gtd.el

    - name: Lint
      run: |
        emacs -Q --batch \
              --eval "(package-initialize)" \
              --eval "(require 'package-lint)" \
              -f package-lint-batch-and-exit emacs/.emacs.d/my/my-org-gtd.el

    - name: Run tests
      run: |
        emacs -Q --batch \
              --eval "(package-initialize)" \
              --eval "(add-to-list 'load-path (expand-file-name \"emacs/.emacs.d/my/\"))" \
              --eval "(require 'ert)" \
              -l my-org-gtd.el \
              -l my-org-gtd-test.el \
              -f ert-run-tests-batch-and-exit
